# Generated by Django 5.2.12 on 2026-03-10 00:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=50)),
                ('niveau', models.CharField(choices=[('MP', 'Serie MP'), ('SVT', 'Serie SVT'), ('SES', 'Serie SES'), ('LLA', 'Serie LLA')], max_length=20)),
                ('option', models.CharField(choices=[('Genie', 'Genie'), ('Medecine', 'Medecine / Sces infirmières'), ('Agronomie', 'Sces agronomiques'), ('Humaines', 'Sces humaines'), ('Education', 'Sces educations'), ('Economiques', 'Sces economiques'), ('Juridiques', 'Sces juridiques')], max_length=50)),
                ('entite', models.CharField(choices=[('FMP', 'FACULTE DE MEDECINE ET DE PHARMACIE'), ('CHCL', 'CAMPUS HENRY CHRISTOPHE DE LIMONADE'), ('FASCH', 'FACULTE DES SCIENCES HUMAINES'), ('EINDS', "ECOLE D'INFIRMIERES NOTRE DAME DE LA SAGESSE DU CAP HAITIEN"), ('ENIP', "ECOLE NATIONALE D'INFIRMIERES DE PORT-AU-PRINCE"), ('EINDPS', 'ECOLE DES INFIRMIERES NOTRE DAME DE PERPETUEL SECOURS DE JEREMIE'), ('ENIC', "ECOLE NATIONALE D'INFIRMIERES DES CAYES"), ('FDSEG-CAP', 'FACULTE DE DROIT, DES SCIENCES ECONOMIQUES ET DE GESTION DU CAP-HAITIEN'), ('EDJ', 'ECOLE DE DROIT DE JACMEL'), ('FLA', 'FACULTE DE LINGUISTIQUE APPLIQUEE'), ('EDSEC', 'ECOLE DE DROIT ET DES SCIENCES ECONOMIQUES DES CAYES'), ('EDH', 'ECOLE DE DROIT DE HINCHE'), ('ENS', 'ECOLE NORMALE SUPERIEURE'), ('FO', "FACULTE D'ODONTOLOGIE"), ('FAMV', "FACULTE D'AGRONOMIE ET DE MEDECINE VETERINAIRE"), ('IERAH', "INSTITUT D'ETUDES ET DE RECHERCHES AFRICAINES D'HAITI"), ('EDSEG', "ECOLE DE DROIT ET D'ECONOMIE DES GONAIVES"), ('INAGHEI', "INSTITUT NATIONAL D'ADMINISTRATION DE GESTION ET DES HAUTES ETUDES INTERNATIONALES"), ('FDSE', 'FACULTE DE DROIT ET DES SCIENCES ECONOMIQUES'), ('FDS', 'FACULTE DES SCIENCES'), ('FE', "FACULTE D'ETHNOLOGIE")], max_length=100)),
                ('score_total', models.IntegerField(default=0)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
