# Generated by Django 5.2.12 on 2026-03-10 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp', '0002_etudiant_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='photo',
            field=models.ImageField(blank=True, default='photos_etudiants/default.png', null=True, upload_to='photos_etudiants/'),
        ),
    ]
