# Generated by Django 5.2.12 on 2026-03-11 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp', '0003_alter_etudiant_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('type_question', models.CharField(choices=[('QCM', 'Choix multiples'), ('VF', 'Vrai/Faux'), ('OUV', 'Réponse ouverte')], default='QCM', max_length=3)),
                ('choix_a', models.CharField(blank=True, max_length=255, null=True)),
                ('choix_b', models.CharField(blank=True, max_length=255, null=True)),
                ('choix_c', models.CharField(blank=True, max_length=255, null=True)),
                ('choix_d', models.CharField(blank=True, max_length=255, null=True)),
                ('reponse_correcte', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True)),
                ('reponse_vf', models.BooleanField(blank=True, null=True)),
                ('reponse_ouverte', models.TextField(blank=True, null=True)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quizapp.matiere')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quizapp.etudiant')),
                ('matiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Quizapp.matiere')),
                ('questions', models.ManyToManyField(to='Quizapp.question')),
            ],
        ),
    ]
