# Generated by Django 3.2.12 on 2026-04-10 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp', '0005_auto_20260409_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='difficulte',
            field=models.IntegerField(choices=[(1, 'Facile'), (2, 'Moyen'), (3, 'Difficile'), (4, 'Très difficile'), (5, 'Extrêmement difficile'), (6, 'Expert'), (7, 'Ancien examen')], default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='niveau_requis',
            field=models.IntegerField(default=1, help_text='Niveau minimum pour accéder à cette question'),
        ),
    ]
