# Generated by Django 4.2.30 on 2026-04-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp', '0008_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='reponse_correcte',
            field=models.CharField(blank=True, help_text='Réponses correctes séparées par des virgules (ex: A ou A,C ou A,B,D)', max_length=10, null=True),
        ),
    ]
