# Generated by Django 4.2.30 on 2026-04-25 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp', '0009_alter_question_reponse_correcte'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_retry_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='parent_quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retry_quizzes', to='Quizapp.quiz'),
        ),
    ]
