# Generated by Django 5.2.12 on 2026-04-27 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp', '0011_simplification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='sujet',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='reponse',
            name='reponse_bool',
        ),
        migrations.RemoveField(
            model_name='reponse',
            name='reponse_choice',
        ),
        migrations.RemoveField(
            model_name='reponse',
            name='reponse_text',
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='entite',
            field=models.CharField(choices=[('FMP', 'FACULTÉ DE MÉDECINE ET DE PHARMACIE'), ('CHCL', 'CAMPUS HENRY CHRISTOPHE DE LIMONADE'), ('FASCH', 'FACULTÉ DES SCIENCES HUMAINES'), ('FDS', 'FACULTÉ DES SCIENCES'), ('FDSE', 'FACULTÉ DE DROIT ET DES SCIENCES ÉCONOMIQUES'), ('ENS', 'ÉCOLE NORMALE SUPÉRIEURE'), ('FAMV', "FACULTÉ D'AGRONOMIE ET DE MÉDECINE VÉTÉRINAIRE"), ('INAGHEI', 'INAGHEI'), ('FE', "FACULTÉ D'ETHNOLOGIE"), ('FLA', 'FACULTÉ DE LINGUISTIQUE APPLIQUÉE'), ('AUTRE', 'Autre')], default='FDS', max_length=100),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='nom_complet',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='option',
            field=models.CharField(choices=[('Genie', 'Génie'), ('Medecine', 'Médecine / Sces infirmières'), ('Agronomie', 'Sces agronomiques'), ('Humaines', 'Sces humaines'), ('Education', 'Sces éducation'), ('Economiques', 'Sces économiques'), ('Juridiques', 'Sces juridiques')], default='Genie', max_length=50),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='serie',
            field=models.CharField(choices=[('MP', 'Série MP'), ('SVT', 'Série SVT'), ('SES', 'Série SES'), ('LLA', 'Série LLA')], default='MP', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('completed', 'Complété'), ('failed', 'Échoué')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulte',
            field=models.IntegerField(choices=[(1, 'Facile'), (2, 'Moyen'), (3, 'Difficile'), (4, 'Très difficile'), (5, 'Expert')], default=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='niveau_requis',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='reponse_correcte',
            field=models.CharField(blank=True, help_text='A, B, C ou D (ou combiné A,C)', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='type_question',
            field=models.CharField(choices=[('QCM', 'Choix multiples'), ('VF', 'Vrai / Faux'), ('OUV', 'Réponse ouverte')], default='QCM', max_length=3),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(blank=True, to='Quizapp.question'),
        ),
    ]
